const mails = [
  {
    'id': 'mail_001',
    'from': {'name' : 'alice', 'address' : 'alice@example.com'},
    'to': [{'name' : 'bob','address' : 'bob@example.com'}],
    'subject': 'Meeting tomorrow',
    'body': 'Hi Bob,\n\nJust confirming our meeting tomorrow at 10:00 AM.\n\nBest,\nAlice',
    'date': '2026-08-15T09:30:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox'],
  },
  {
    'id': 'mail_002',
    'from': {'name' : 'techdaily', 'address' : 'newsletter@techdaily.example'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your weekly tech roundup',
    'body': 'Here are this week\'s top technology stories, product launches, and industry updates.',
    'date': '2026-08-14T18:15:00+02:00',
    'read': false,
    'starred': true,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_003',
    'from': {'name' : 'sarah', 'address' : 'sarah@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Project update',
    'body': 'The latest version of the project is ready for review. I\'ve included the requested changes.',
    'date': '2026-08-14T14:20:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox', 'important', 'snoozed'],
  },
  {
    'id': 'mail_004',
    'from': {'name' : 'store', 'address' : 'store@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your order has shipped',
    'body': 'Good news! Your order #12345 has shipped and is on its way.',
    'date': '2026-08-13T11:05:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox', 'shopping'],
  },
  {
    'id': 'mail_005',
    'from': {'name' : 'newsletter', 'address' : 'newsletter@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'August newsletter',
    'body': 'Check out our latest news, announcements, and upcoming events.',
    'date': '2026-08-12T08:00:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_006',
    'from': {'name' : 'bob', 'address' : 'bob@example.com'},
    'to': [{'name' : 'team', 'address' : 'team@example.com'}],
    'subject': 'Re: Design review',
    'body': 'Thanks everyone. I\'ll incorporate the feedback and share an updated version tomorrow.',
    'date': '2026-08-11T16:45:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['sent'],
  },{
    'id': 'mail_001',
    'from': {'name' : 'alice', 'address' : 'alice@example.com'},
    'to': [{'name' : 'bob','address' : 'bob@example.com'}],
    'subject': 'Meeting tomorrow',
    'body': 'Hi Bob,\n\nJust confirming our meeting tomorrow at 10:00 AM.\n\nBest,\nAlice',
    'date': '2026-08-15T09:30:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox'],
  },
  {
    'id': 'mail_002',
    'from': {'name' : 'techdaily', 'address' : 'newsletter@techdaily.example'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your weekly tech roundup',
    'body': 'Here are this week\'s top technology stories, product launches, and industry updates.',
    'date': '2026-08-14T18:15:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_003',
    'from': {'name' : 'sarah', 'address' : 'sarah@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Project update',
    'body': 'The latest version of the project is ready for review. I\'ve included the requested changes.',
    'date': '2026-08-14T14:20:00+02:00',
    'read': true,
    'starred': true,
    'labels': ['inbox', 'important', 'snoozed'],
  },
  {
    'id': 'mail_004',
    'from': {'name' : 'store', 'address' : 'store@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your order has shipped',
    'body': 'Good news! Your order #12345 has shipped and is on its way.',
    'date': '2026-08-13T11:05:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox', 'shopping'],
  },
  {
    'id': 'mail_005',
    'from': {'name' : 'newsletter', 'address' : 'newsletter@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'August newsletter',
    'body': 'Check out our latest news, announcements, and upcoming events.',
    'date': '2026-08-12T08:00:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_006',
    'from': {'name' : 'bob', 'address' : 'bob@example.com'},
    'to': [{'name' : 'team', 'address' : 'team@example.com'}],
    'subject': 'Re: Design review',
    'body': 'Thanks everyone. I\'ll incorporate the feedback and share an updated version tomorrow.',
    'date': '2026-08-11T16:45:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['sent'],
  },{
    'id': 'mail_001',
    'from': {'name' : 'alice', 'address' : 'alice@example.com'},
    'to': [{'name' : 'bob','address' : 'bob@example.com'}],
    'subject': 'Meeting tomorrow',
    'body': 'Hi Bob,\n\nJust confirming our meeting tomorrow at 10:00 AM.\n\nBest,\nAlice',
    'date': '2026-08-15T09:30:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox'],
  },
  {
    'id': 'mail_002',
    'from': {'name' : 'techdaily', 'address' : 'newsletter@techdaily.example'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your weekly tech roundup',
    'body': 'Here are this week\'s top technology stories, product launches, and industry updates.',
    'date': '2026-08-14T18:15:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_003',
    'from': {'name' : 'sarah', 'address' : 'sarah@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Project update',
    'body': 'The latest version of the project is ready for review. I\'ve included the requested changes.',
    'date': '2026-08-14T14:20:00+02:00',
    'read': true,
    'starred': true,
    'labels': ['inbox', 'important', 'snoozed'],
  },
  {
    'id': 'mail_004',
    'from': {'name' : 'store', 'address' : 'store@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your order has shipped',
    'body': 'Good news! Your order #12345 has shipped and is on its way.',
    'date': '2026-08-13T11:05:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox', 'shopping'],
  },
  {
    'id': 'mail_005',
    'from': {'name' : 'newsletter', 'address' : 'newsletter@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'August newsletter',
    'body': 'Check out our latest news, announcements, and upcoming events.',
    'date': '2026-08-12T08:00:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_006',
    'from': {'name' : 'bob', 'address' : 'bob@example.com'},
    'to': [{'name' : 'team', 'address' : 'team@example.com'}],
    'subject': 'Re: Design review',
    'body': 'Thanks everyone. I\'ll incorporate the feedback and share an updated version tomorrow.',
    'date': '2026-08-11T16:45:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['sent'],
  },{
    'id': 'mail_001',
    'from': {'name' : 'alice', 'address' : 'alice@example.com'},
    'to': [{'name' : 'bob','address' : 'bob@example.com'}],
    'subject': 'Meeting tomorrow',
    'body': 'Hi Bob,\n\nJust confirming our meeting tomorrow at 10:00 AM.\n\nBest,\nAlice',
    'date': '2026-08-15T09:30:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox'],
  },
  {
    'id': 'mail_002',
    'from': {'name' : 'techdaily', 'address' : 'newsletter@techdaily.example'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your weekly tech roundup',
    'body': 'Here are this week\'s top technology stories, product launches, and industry updates.',
    'date': '2026-08-14T18:15:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_003',
    'from': {'name' : 'sarah', 'address' : 'sarah@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Project update',
    'body': 'The latest version of the project is ready for review. I\'ve included the requested changes.',
    'date': '2026-08-14T14:20:00+02:00',
    'read': true,
    'starred': true,
    'labels': ['inbox', 'important', 'snoozed'],
  },
  {
    'id': 'mail_004',
    'from': {'name' : 'store', 'address' : 'store@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your order has shipped',
    'body': 'Good news! Your order #12345 has shipped and is on its way.',
    'date': '2026-08-13T11:05:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox', 'shopping'],
  },
  {
    'id': 'mail_005',
    'from': {'name' : 'newsletter', 'address' : 'newsletter@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'August newsletter',
    'body': 'Check out our latest news, announcements, and upcoming events.',
    'date': '2026-08-12T08:00:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_006',
    'from': {'name' : 'bob', 'address' : 'bob@example.com'},
    'to': [{'name' : 'team', 'address' : 'team@example.com'}],
    'subject': 'Re: Design review',
    'body': 'Thanks everyone. I\'ll incorporate the feedback and share an updated version tomorrow.',
    'date': '2026-08-11T16:45:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['sent'],
  },{
    'id': 'mail_001',
    'from': {'name' : 'alice', 'address' : 'alice@example.com'},
    'to': [{'name' : 'bob','address' : 'bob@example.com'}],
    'subject': 'Meeting tomorrow',
    'body': 'Hi Bob,\n\nJust confirming our meeting tomorrow at 10:00 AM.\n\nBest,\nAlice',
    'date': '2026-08-15T09:30:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox'],
  },
  {
    'id': 'mail_002',
    'from': {'name' : 'techdaily', 'address' : 'newsletter@techdaily.example'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your weekly tech roundup',
    'body': 'Here are this week\'s top technology stories, product launches, and industry updates.',
    'date': '2026-08-14T18:15:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_003',
    'from': {'name' : 'sarah', 'address' : 'sarah@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Project update',
    'body': 'The latest version of the project is ready for review. I\'ve included the requested changes.',
    'date': '2026-08-14T14:20:00+02:00',
    'read': true,
    'starred': true,
    'labels': ['inbox', 'important', 'snoozed'],
  },
  {
    'id': 'mail_004',
    'from': {'name' : 'store', 'address' : 'store@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your order has shipped',
    'body': 'Good news! Your order #12345 has shipped and is on its way.',
    'date': '2026-08-13T11:05:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox', 'shopping'],
  },
  {
    'id': 'mail_005',
    'from': {'name' : 'newsletter', 'address' : 'newsletter@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'August newsletter',
    'body': 'Check out our latest news, announcements, and upcoming events.',
    'date': '2026-08-12T08:00:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_006',
    'from': {'name' : 'bob', 'address' : 'bob@example.com'},
    'to': [{'name' : 'team', 'address' : 'team@example.com'}],
    'subject': 'Re: Design review',
    'body': 'Thanks everyone. I\'ll incorporate the feedback and share an updated version tomorrow.',
    'date': '2026-08-11T16:45:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['sent'],
  },{
    'id': 'mail_001',
    'from': {'name' : 'alice', 'address' : 'alice@example.com'},
    'to': [{'name' : 'bob','address' : 'bob@example.com'}],
    'subject': 'Meeting tomorrow',
    'body': 'Hi Bob,\n\nJust confirming our meeting tomorrow at 10:00 AM.\n\nBest,\nAlice',
    'date': '2026-08-15T09:30:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox'],
  },
  {
    'id': 'mail_002',
    'from': {'name' : 'techdaily', 'address' : 'newsletter@techdaily.example'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your weekly tech roundup',
    'body': 'Here are this week\'s top technology stories, product launches, and industry updates.',
    'date': '2026-08-14T18:15:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_003',
    'from': {'name' : 'sarah', 'address' : 'sarah@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Project update',
    'body': 'The latest version of the project is ready for review. I\'ve included the requested changes.',
    'date': '2026-08-14T14:20:00+02:00',
    'read': true,
    'starred': true,
    'labels': ['inbox', 'important', 'snoozed'],
  },
  {
    'id': 'mail_004',
    'from': {'name' : 'store', 'address' : 'store@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'Your order has shipped',
    'body': 'Good news! Your order #12345 has shipped and is on its way.',
    'date': '2026-08-13T11:05:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['inbox', 'shopping'],
  },
  {
    'id': 'mail_005',
    'from': {'name' : 'newsletter', 'address' : 'newsletter@example.com'},
    'to': [{'name' : 'bob', 'address' : 'bob@example.com'}],
    'subject': 'August newsletter',
    'body': 'Check out our latest news, announcements, and upcoming events.',
    'date': '2026-08-12T08:00:00+02:00',
    'read': false,
    'starred': false,
    'labels': ['inbox', 'newsletter'],
  },
  {
    'id': 'mail_006',
    'from': {'name' : 'bob', 'address' : 'bob@example.com'},
    'to': [{'name' : 'team', 'address' : 'team@example.com'}],
    'subject': 'Re: Design review',
    'body': 'Thanks everyone. I\'ll incorporate the feedback and share an updated version tomorrow.',
    'date': '2026-08-11T16:45:00+02:00',
    'read': true,
    'starred': false,
    'labels': ['sent'],
  },
];

export default mails;